import { Suspense, useMemo, useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { PerspectiveCamera }           from '@react-three/drei';
import { EffectComposer, Bloom }       from '@react-three/postprocessing';
import * as THREE                      from 'three';
import GlowingPath                     from './GlowingPath.jsx';

/**
 * ARScene — SafeLine
 *
 * Builds a CatmullRomCurve3 directly from ticket.waypoints (dynamically
 * generated by pathGenerator.js — no static PATHS lookup).
 *
 * CameraController physically moves and orients the camera along the spline
 * based on journey progress (0–1), creating real guided navigation movement.
 */

// ── Pre-allocated Three.js objects (avoid GC pressure in useFrame) ──────────
const _fwd        = new THREE.Vector3();
const _camPos3D   = new THREE.Vector3();
const _lookPos3D  = new THREE.Vector3();
const _targetQuat = new THREE.Quaternion();
const _localFwd   = new THREE.Vector3(0, 0, -1); // camera default forward

// ── Fallback if waypoints missing ───────────────────────────────────────────
const FALLBACK_WAYPOINTS = [
  [0, -0.5, 0], [0, -0.5, -2], [0, -0.5, -4],
  [0, -0.5, -6], [-2, -0.5, -6], [-6, -0.5, -6],
];

/**
 * CameraController
 *
 * Physically moves + rotates the camera along the spline:
 *  - XZ position: lerp toward curve.getPoint(t)
 *  - Y position:  lerp toward 0 (eye level)
 *  - Orientation: quaternion slerp toward look-ahead tangent direction
 *
 * Produces true 90° turns delivered via smooth interpolation — not fake tilts.
 */
function CameraController({ curve, progress }) {
  const { camera } = useThree();
  const visualProgress = useRef(0);

  useFrame(({ gl }, delta) => {
    if (gl.xr?.isPresenting) return;
    if (delta <= 0 || delta > 0.1) return;

    // Smooth visual progress — creates gradual forward movement feel
    visualProgress.current = THREE.MathUtils.lerp(
      visualProgress.current,
      Math.max(0, Math.min(1, progress)),
      delta * 0.65
    );

    const t     = visualProgress.current;
    const tLook = Math.min(t + 0.06, 1.0); // look 6% ahead

    curve.getPoint(t,     _camPos3D);
    curve.getPoint(tLook, _lookPos3D);

    // Smooth XZ camera position at eye level
    camera.position.x = THREE.MathUtils.lerp(camera.position.x, _camPos3D.x, delta * 2.2);
    camera.position.z = THREE.MathUtils.lerp(camera.position.z, _camPos3D.z, delta * 2.2);
    camera.position.y = THREE.MathUtils.lerp(camera.position.y, 0,           delta * 4.0);

    // Compute forward direction (XZ only — keep camera level)
    _fwd.set(
      _lookPos3D.x - camera.position.x,
      0,
      _lookPos3D.z - camera.position.z
    );

    if (_fwd.length() > 0.001) {
      _fwd.normalize();
      // Build target quaternion: rotate from camera local -Z to world forward
      _targetQuat.setFromUnitVectors(_localFwd, _fwd);
      // Slerp ~0.35s for smooth 90° turn feel
      camera.quaternion.slerp(_targetQuat, delta * 2.8);
    }
  });

  return null;
}

// ── Main scene component ─────────────────────────────────────────────────────
/**
 * @param {object} ticket    — full ticket from generateTicket()
 * @param {number} progress  — 0 (start) to 1 (destination)
 */
export default function ARScene({ ticket, progress = 0 }) {
  const { color, waypoints: rawWaypoints } = ticket;
  const sourceWaypoints = rawWaypoints ?? FALLBACK_WAYPOINTS;

  // Build spline from dynamic waypoints
  const curve = useMemo(() => {
    const pts = sourceWaypoints.map(([x, y, z]) => new THREE.Vector3(x, y, z));
    return new THREE.CatmullRomCurve3(pts, false, 'catmullrom', 0.5);
  }, [sourceWaypoints]);

  return (
    <Canvas
      id="ar-three-canvas"
      style={{ position: 'absolute', inset: 0, background: 'transparent' }}
      gl={{ alpha: true, antialias: true, powerPreference: 'high-performance' }}
      onCreated={({ gl }) => { gl.toneMapping = 0; }} // NoToneMapping
    >
      <PerspectiveCamera makeDefault position={[0, 0, 0]} fov={75} near={0.01} far={100} />

      {/* Camera follows the dynamic path spline */}
      <CameraController curve={curve} progress={progress} />

      <ambientLight intensity={0.3} />
      <pointLight position={[0, 1, 0]} intensity={1.5} color={color} />

      {/* Single dynamic path — new geometry every scan */}
      <Suspense fallback={null}>
        <GlowingPath color={color} waypoints={sourceWaypoints} active={true} />
      </Suspense>

      {/* Bloom post-processing */}
      <EffectComposer>
        <Bloom intensity={1.8} luminanceThreshold={0.1} luminanceSmoothing={0.9} mipmapBlur />
      </EffectComposer>
    </Canvas>
  );
}
